// Code generated by protoc-gen-go.
// source: cliproto_up.proto
// DO NOT EDIT!

package cliproto_up

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Authenticate struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	SessionId        *uint64 `protobuf:"varint,3,req,name=sessionId" json:"sessionId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Authenticate) Reset()         { *m = Authenticate{} }
func (m *Authenticate) String() string { return proto.CompactTextString(m) }
func (*Authenticate) ProtoMessage()    {}

func (m *Authenticate) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Authenticate) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Authenticate) GetSessionId() uint64 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type FollowUsername struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FollowUsername) Reset()         { *m = FollowUsername{} }
func (m *FollowUsername) String() string { return proto.CompactTextString(m) }
func (*FollowUsername) ProtoMessage()    {}

func (m *FollowUsername) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type FollowUser struct {
	UserId           *uint64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FollowUser) Reset()         { *m = FollowUser{} }
func (m *FollowUser) String() string { return proto.CompactTextString(m) }
func (*FollowUser) ProtoMessage()    {}

func (m *FollowUser) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type StopFollowingUser struct {
	UserId           *uint64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopFollowingUser) Reset()         { *m = StopFollowingUser{} }
func (m *StopFollowingUser) String() string { return proto.CompactTextString(m) }
func (*StopFollowingUser) ProtoMessage()    {}

func (m *StopFollowingUser) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type Send struct {
	Recipient        *uint64 `protobuf:"varint,1,req,name=recipient" json:"recipient,omitempty"`
	Tag              *string `protobuf:"bytes,2,req,name=tag" json:"tag,omitempty"`
	Content          *string `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Send) Reset()         { *m = Send{} }
func (m *Send) String() string { return proto.CompactTextString(m) }
func (*Send) ProtoMessage()    {}

func (m *Send) GetRecipient() uint64 {
	if m != nil && m.Recipient != nil {
		return *m.Recipient
	}
	return 0
}

func (m *Send) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *Send) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
}
