// Code generated by protoc-gen-go.
// source: baseproto.proto
// DO NOT EDIT!

package baseproto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Message struct {
	MsgType          *uint32 `protobuf:"varint,1,req,name=msgType" json:"msgType,omitempty"`
	Content          []byte  `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Capabilities struct {
	Capabilities     []string `protobuf:"bytes,1,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Capabilities) Reset()         { *m = Capabilities{} }
func (m *Capabilities) String() string { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()    {}

func (m *Capabilities) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func init() {
}
