// Code generated by protoc-gen-go.
// source: shared/chrequest/chproto/chproto.proto
// DO NOT EDIT!

package chproto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Change struct {
	TargetEntity     *uint64 `protobuf:"varint,1,req,name=targetEntity" json:"targetEntity,omitempty"`
	Key              *string `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}

func (m *Change) GetTargetEntity() uint64 {
	if m != nil && m.TargetEntity != nil {
		return *m.TargetEntity
	}
	return 0
}

func (m *Change) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Change) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type ChangeRequest struct {
	RequestEntity    *uint64   `protobuf:"varint,1,req,name=requestEntity" json:"requestEntity,omitempty"`
	RequestNode      *uint32   `protobuf:"varint,2,req,name=requestNode" json:"requestNode,omitempty"`
	RequestId        *uint64   `protobuf:"varint,3,req,name=requestId" json:"requestId,omitempty"`
	Changeset        []*Change `protobuf:"bytes,4,rep,name=changeset" json:"changeset,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ChangeRequest) Reset()         { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()    {}

func (m *ChangeRequest) GetRequestEntity() uint64 {
	if m != nil && m.RequestEntity != nil {
		return *m.RequestEntity
	}
	return 0
}

func (m *ChangeRequest) GetRequestNode() uint32 {
	if m != nil && m.RequestNode != nil {
		return *m.RequestNode
	}
	return 0
}

func (m *ChangeRequest) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *ChangeRequest) GetChangeset() []*Change {
	if m != nil {
		return m.Changeset
	}
	return nil
}

type ChangeForward struct {
	Request          *ChangeRequest `protobuf:"bytes,1,req,name=request" json:"request,omitempty"`
	Ignores          []uint32       `protobuf:"varint,2,rep,name=ignores" json:"ignores,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ChangeForward) Reset()         { *m = ChangeForward{} }
func (m *ChangeForward) String() string { return proto.CompactTextString(m) }
func (*ChangeForward) ProtoMessage()    {}

func (m *ChangeForward) GetRequest() *ChangeRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ChangeForward) GetIgnores() []uint32 {
	if m != nil {
		return m.Ignores
	}
	return nil
}

type ChangeForwardAck struct {
	RequestNode      *uint32 `protobuf:"varint,1,req,name=requestNode" json:"requestNode,omitempty"`
	RequestId        *uint64 `protobuf:"varint,2,req,name=requestId" json:"requestId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChangeForwardAck) Reset()         { *m = ChangeForwardAck{} }
func (m *ChangeForwardAck) String() string { return proto.CompactTextString(m) }
func (*ChangeForwardAck) ProtoMessage()    {}

func (m *ChangeForwardAck) GetRequestNode() uint32 {
	if m != nil && m.RequestNode != nil {
		return *m.RequestNode
	}
	return 0
}

func (m *ChangeForwardAck) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func init() {
}
