// Code generated by protoc-gen-go.
// source: cliproto_down.proto
// DO NOT EDIT!

package cliproto_down

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AuthenticationFailed struct {
	Reason           *string `protobuf:"bytes,1,req,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticationFailed) Reset()         { *m = AuthenticationFailed{} }
func (m *AuthenticationFailed) String() string { return proto.CompactTextString(m) }
func (*AuthenticationFailed) ProtoMessage()    {}

func (m *AuthenticationFailed) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type AuthenticationSuccess struct {
	SessionId        *uint64 `protobuf:"varint,1,req,name=sessionId" json:"sessionId,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthenticationSuccess) Reset()         { *m = AuthenticationSuccess{} }
func (m *AuthenticationSuccess) String() string { return proto.CompactTextString(m) }
func (*AuthenticationSuccess) ProtoMessage()    {}

func (m *AuthenticationSuccess) GetSessionId() uint64 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *AuthenticationSuccess) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type FollowFailed struct {
	FirstUnapplied   *uint64 `protobuf:"varint,1,req,name=firstUnapplied" json:"firstUnapplied,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	Reason           *string `protobuf:"bytes,3,req,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FollowFailed) Reset()         { *m = FollowFailed{} }
func (m *FollowFailed) String() string { return proto.CompactTextString(m) }
func (*FollowFailed) ProtoMessage()    {}

func (m *FollowFailed) GetFirstUnapplied() uint64 {
	if m != nil && m.FirstUnapplied != nil {
		return *m.FirstUnapplied
	}
	return 0
}

func (m *FollowFailed) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *FollowFailed) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type Following struct {
	FirstUnapplied   *uint64 `protobuf:"varint,1,req,name=firstUnapplied" json:"firstUnapplied,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	UserId           *uint64 `protobuf:"varint,3,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Following) Reset()         { *m = Following{} }
func (m *Following) String() string { return proto.CompactTextString(m) }
func (*Following) ProtoMessage()    {}

func (m *Following) GetFirstUnapplied() uint64 {
	if m != nil && m.FirstUnapplied != nil {
		return *m.FirstUnapplied
	}
	return 0
}

func (m *Following) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Following) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type UserData struct {
	FirstUnapplied   *uint64 `protobuf:"varint,1,req,name=firstUnapplied" json:"firstUnapplied,omitempty"`
	UserId           *uint64 `protobuf:"varint,2,req,name=userId" json:"userId,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,4,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}

func (m *UserData) GetFirstUnapplied() uint64 {
	if m != nil && m.FirstUnapplied != nil {
		return *m.FirstUnapplied
	}
	return 0
}

func (m *UserData) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *UserData) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *UserData) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type UserDataDone struct {
	FirstUnapplied   *uint64 `protobuf:"varint,1,req,name=firstUnapplied" json:"firstUnapplied,omitempty"`
	UserId           *uint64 `protobuf:"varint,2,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserDataDone) Reset()         { *m = UserDataDone{} }
func (m *UserDataDone) String() string { return proto.CompactTextString(m) }
func (*UserDataDone) ProtoMessage()    {}

func (m *UserDataDone) GetFirstUnapplied() uint64 {
	if m != nil && m.FirstUnapplied != nil {
		return *m.FirstUnapplied
	}
	return 0
}

func (m *UserDataDone) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type UserDataChange struct {
	FirstUnapplied   *uint64 `protobuf:"varint,1,req,name=firstUnapplied" json:"firstUnapplied,omitempty"`
	UserId           *uint64 `protobuf:"varint,2,req,name=userId" json:"userId,omitempty"`
	Key              *string `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,4,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserDataChange) Reset()         { *m = UserDataChange{} }
func (m *UserDataChange) String() string { return proto.CompactTextString(m) }
func (*UserDataChange) ProtoMessage()    {}

func (m *UserDataChange) GetFirstUnapplied() uint64 {
	if m != nil && m.FirstUnapplied != nil {
		return *m.FirstUnapplied
	}
	return 0
}

func (m *UserDataChange) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *UserDataChange) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *UserDataChange) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type StoppedFollowing struct {
	UserId           *uint64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Reason           *string `protobuf:"bytes,2,req,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StoppedFollowing) Reset()         { *m = StoppedFollowing{} }
func (m *StoppedFollowing) String() string { return proto.CompactTextString(m) }
func (*StoppedFollowing) ProtoMessage()    {}

func (m *StoppedFollowing) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *StoppedFollowing) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type Received struct {
	SenderUserId     *uint64 `protobuf:"varint,1,req,name=senderUserId" json:"senderUserId,omitempty"`
	SenderSessionId  *uint64 `protobuf:"varint,2,req,name=senderSessionId" json:"senderSessionId,omitempty"`
	Tag              *string `protobuf:"bytes,3,req,name=tag" json:"tag,omitempty"`
	Content          *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Received) Reset()         { *m = Received{} }
func (m *Received) String() string { return proto.CompactTextString(m) }
func (*Received) ProtoMessage()    {}

func (m *Received) GetSenderUserId() uint64 {
	if m != nil && m.SenderUserId != nil {
		return *m.SenderUserId
	}
	return 0
}

func (m *Received) GetSenderSessionId() uint64 {
	if m != nil && m.SenderSessionId != nil {
		return *m.SenderSessionId
	}
	return 0
}

func (m *Received) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *Received) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
}
